apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T06:44:46Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4160"
  uid: 4dff92d1-8f50-498a-a557-fad1a136da2f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.156.80
  clusterIPs:
  - 10.109.156.80
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32097
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
